### ISSUE TITLE
non standard ASCII char

### ISSUE THREAD

**Issue by intel2004** [nickgammon/MAX7219#2]
i try this library,is very cool.
but in NON-ASCII char there is some problem...
because i'm italian, the chars "à" "è" "ì" "ò" "ù" is much in use.
if i put these chars in "DEMO" and in "SCROLLING" i see correct greek character,
if i put these chars in "SMOOTH_SCROLLING" i see a strange char, apparently any in the font.h
if necessary i will edit the font.h with correct ones, but is useless if not work in smooth mode!
can you help me, please?
thanks

**Comment by nickgammon** [comment]
Fixed in commit https://github.com/nickgammon/MAX7219_Dot_Matrix/commit/1210f235ba8349ac913414f7b2668d60c4adfe57

Note that this bug report was attached to the wrong library. You want https://github.com/nickgammon/MAX7219_Dot_Matrix - that's the one with the smooth scrolling.
